name: Release

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run build
      - run: aws configure set default.s3.max_concurrent_requests 3
  
      - name: upload file
        run: aws --endpoint-url "${ENDPOINT_URL}" s3 sync ./build s3://${BUCKET_NAME}/zmm/doc --delete
        env:
          ENDPOINT_URL: ${{ secrets.ENDPOINT_URL }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: auto # avoid botocore.awsrequest.AWSRequest error
